project:
  type: website 
  output-dir: docs
  
website:
  title: "Sechang Kim"
  favicon: img/favicon.ico
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
          - text: Migration
          - text: Education
      - text: Teaching
        menu:
          - text: Instructor
          - text: Teaching Assistant
      - href: personal-experience.qmd
        text: Personal Experience
      - href: blog.qmd
        text: Blog
        
format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.0rem
    theme:
      - custom.scss
    mainfont: Pretendard

editor: visual

