project:
  type: website 
  output-dir: docs
  
website:
  title: "Sechang Kim"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Research
        menu:
          - text: Migration
          - text: Education
      - text: Teaching
        menu:
          - text: Instructor
          - text: Teaching Assistant
<<<<<<< HEAD
      - href: blog.qmd
        text: Blog
=======
      - href: personal-experience.qmd
        text: Personal Experience
      - href: Travel_Takamatsu.qmd
        text: Travel
>>>>>>> bc3885be287537538c4aa6cf660b1f87ac8a0dc6
        
format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.0rem
    theme:
      - custom.scss
    mainfont: Pretendard

editor: visual

